/** Additive schema: existing orders/Telegram status columns stay unchanged. */
export const CHECKOUT_SCHEMA = [
  `CREATE TABLE IF NOT EXISTS order_submissions (request_key TEXT PRIMARY KEY NOT NULL, user_id INTEGER NOT NULL, order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE, request_hash TEXT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS order_submissions_order_idx ON order_submissions(order_id)`,
  `CREATE TRIGGER IF NOT EXISTS checkout_item_guard BEFORE INSERT ON order_items WHEN EXISTS (SELECT 1 FROM order_submissions WHERE order_id = NEW.order_id) BEGIN SELECT CASE WHEN NEW.quantity <= 0 OR NEW.unit_price < 0 THEN RAISE(ABORT, 'CHECKOUT_PRICE_CHANGED') WHEN NOT EXISTS (SELECT 1 FROM products WHERE id = NEW.product_id AND is_active = 1 AND COALESCE(stock, 0) >= NEW.quantity) THEN RAISE(ABORT, 'CHECKOUT_STOCK_CHANGED') END; END`,
  `CREATE TRIGGER IF NOT EXISTS checkout_reserve_stock AFTER INSERT ON order_items WHEN EXISTS (SELECT 1 FROM order_submissions WHERE order_id = NEW.order_id) BEGIN UPDATE products SET stock = stock - NEW.quantity WHERE id = NEW.product_id; END`,
  `CREATE TRIGGER IF NOT EXISTS checkout_release_stock AFTER UPDATE OF status ON orders WHEN OLD.status IN ('pending', 'approved') AND NEW.status = 'rejected' AND EXISTS (SELECT 1 FROM order_submissions WHERE order_id = OLD.id) BEGIN UPDATE products SET stock = stock + (SELECT COALESCE(SUM(quantity), 0) FROM order_items WHERE order_id = OLD.id AND product_id = products.id) WHERE id IN (SELECT product_id FROM order_items WHERE order_id = OLD.id); END`,
  `CREATE TRIGGER IF NOT EXISTS checkout_rejected_terminal BEFORE UPDATE OF status ON orders WHEN OLD.status = 'rejected' AND NEW.status <> 'rejected' AND EXISTS (SELECT 1 FROM order_submissions WHERE order_id = OLD.id) BEGIN SELECT RAISE(ABORT, 'CHECKOUT_REJECTED_TERMINAL'); END`,
  `CREATE TRIGGER IF NOT EXISTS checkout_delete_release BEFORE DELETE ON orders WHEN OLD.status IN ('pending', 'approved') AND EXISTS (SELECT 1 FROM order_submissions WHERE order_id = OLD.id) BEGIN UPDATE products SET stock = stock + (SELECT COALESCE(SUM(quantity), 0) FROM order_items WHERE order_id = OLD.id AND product_id = products.id) WHERE id IN (SELECT product_id FROM order_items WHERE order_id = OLD.id); END`,
];
